@Host = http://localhost:5108

GET {{Host}}/report/unknown-token

###

POST {{Host}}/telegram/webhook
Content-Type: application/json
X-Telegram-Bot-Api-Secret-Token: your-webhook-secret

{
  "update_id": 1
}

###
